# Generated by Django 5.0.4 on 2024-04-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieinfo',
            name='rating',
            field=models.CharField(default='SOME STRING', max_length=20),
        ),
    ]
