# Generated by Django 5.0.4 on 2024-04-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movieinfo_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieinfo',
            name='rating',
            field=models.CharField(max_length=20),
        ),
    ]
