# Generated by Django 5.0.4 on 2024-04-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movieinfo_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieinfo',
            name='image',
            field=models.CharField(default='fstdf', max_length=200),
        ),
    ]
