# Generated by Django 5.0.4 on 2024-04-17 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movieinfo_rating'),
        ('movies', '0003_movieinfo_image'),
    ]

    operations = [
    ]
