# Generated by Django 5.0.4 on 2024-04-17 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_merge_20240417_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieinfo',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
